/* Public header for the LPC17xx clock controller driver */

#ifndef ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_LPC17XX_CLOCK_CONTROL_H_
#define ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_LPC17XX_CLOCK_CONTROL_H_

#include <zephyr/devicetree.h>
#include <zephyr/drivers/clock_control.h>

/* Fixed clocks */
#define LPC17XX_IRC_OSC DT_NODELABEL(irc_osc)
#define LPC17XX_IRC_OSC_ENABLED DT_NODE_HAS_STATUS_OKAY(LPC17XX_IRC_OSC)
#define LPC17XX_IRC_OSC_FREQ DT_PROP_OR(LPC17XX_IRC_OSC, clock_frequency, 0)
#define LPC17XX_OSC_CLK DT_NODELABEL(osc_clk)
#define LPC17XX_OSC_CLK_ENABLED DT_NODE_HAS_STATUS_OKAY(LPC17XX_OSC_CLK)
#define LPC17XX_OSC_CLK_FREQ DT_PROP_OR(LPC17XX_OSC_CLK, clock_frequency, 0)
#define LPC17XX_RTC_CLK DT_NODELABEL(rtc_clk)
#define LPC17XX_RTC_CLK_ENABLED DT_NODE_HAS_STATUS_OKAY(LPC17XX_RTC_CLK)
#define LPC17XX_RTC_CLK_FREQ DT_PROP_OR(LPC17XX_RTC_CLK, clock_frequency, 0)

/* PLLs */
#define LPC17XX_MAIN_PLL DT_INST(0, nxp_lpc17xx_main_pll)
#define LPC17XX_MAIN_PLL_ENABLED DT_NODE_HAS_STATUS_OKAY(LPC17XX_MAIN_PLL)
#define LPC17XX_USB_PLL DT_INST(0, nxp_lpc17xx_usb_pll)
#define LPC17XX_USB_PLL_ENABLED DT_NODE_HAS_STATUS_OKAY(LPC17XX_USB_PLL)

/* Clock controller */
#define LPC17XX_CLOCK_CONTROL DT_INST(0, nxp_lpc17xx_clock)

#endif /* ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_LPC17XX_CLOCK_CONTROL_H_ */
